### ISSUE TITLE
gnus-desktop-notify-explicit not working

### ISSUE THREAD

**Issue by a-schaefers** [wavexx/gnus-desktop-notify.el#13]
FreeBSD 11.1 / spacemacs / gmail / imap

Hi, after several hours today, I have come to conclusion:

1. Gnus-desktop-notify works as expected, displaying notifications for all groups by default, no problems.

2. Gnus-desktop-notify will show notifications for explicitly selected groups with the following configuration, no problems:

```
;; Daemon to fetch email every ~5 mins (checks while emacs is idle)
(gnus-demon-add-handler 'gnus-demon-scan-news 5 t)

;; Use notify-send for desktop notifications on new mail
(require 'gnus-desktop-notify)
(setq gnus-desktop-notify-function 'gnus-desktop-notify-exec
      gnus-desktop-notify-exec-program "notify-send")
(gnus-desktop-notify-mode)
(gnus-demon-add-scanmail)

;; Only send desktop notifications for groups selected
;; by pressing 'G c' on the group and then checking the relevant notification box setting.
(setq gnus-desktop-notify-groups 'gnus-desktop-notify-explicit)
```

Caveats: I am unable to maintain all of my settings within gnus.el, and have to manually reconfigure within gnus via 'G c' for each group that I want to receive desktop notifications. It would be nice to set notification groups within gnus.el.

**3. Gnus-desktop-notify feature to explicitly set notifiction groups from within gnus.el has no effect:
The following eg. having both a group named "INBOX" and a group named "00.FAMILY" does not work:**
```
(setq gnus-desktop-notify-groups 'gnus-desktop-notify-explicit)
(setq gnus-parameters
   '(("INBOX"     (group-notify t))
     ("00.FAMILY" (group-notify t))))
```

**Expected result**: Receive desktop notifications for only my INBOX group and my 00.FAMILY group, but no other groups.
**Actual result**: Received zero notifications for any group.

It would be nice if we could find a way to get this working, I'd prefer to set my notification groups solely within gnus.el and not have to fiddle within gnus group settings via "G c"

If you would like me to test anything further in helping debug this, or if I have made an elementary mistake, please let me know. I am glad to have a desktop-notifier for my email. Thank You.

**Comment by basil-conto** [comment]
FWIW, I'd like to try and help with this issue and #14, but I don't expect to find the time for another couple of weeks; sorry.
