### ISSUE TITLE
avoid alert about message to my self (gcc)

### ISSUE THREAD

**Issue by tagteam** [wavexx/gnus-desktop-notify.el#7]
Is there a way to not get alerted about messages that I sent out and copy (marked as read) to one of my groups (gcc)? 

This is a very nice package. Thank you!

**Comment by wavexx** [comment]
Do you copy to a group that also receives new mail?

**Comment by tagteam** [comment]
yes, in order to see all mails of a thread in one summary buffer

**Comment by wavexx** [comment]
Let's drag @basil-conto in. We should be already using the unread count to check for new mail, so if the message is already marked as read, you shouldn't be notified.

**Comment by tagteam** [comment]
did some e-debugging and agree with you -- I should not be notified. actually right now I cannot reproduce my own problem. so this is good. also, if it should re-appear, I can update gnus-desktop-notify-counts somehow in connection with message-sent-hook and gnus-inews-do-gcc

**Comment by basil-conto** [comment]
For what it's worth, I am not entirely familiar with how the read/unread/unseen counts are maintained/calculated in either gnus or gnus-desktop-notify yet, but it is an area I've slowly been looking into. Let me know if this or any further issues arise, though I can't promise either timely nor useful input on my part for the next while.
